version: "3"
services:
  nginx:
    container_name: "vueapp"
    image: nginx:1.13.3-alpine
    ports:
      - 8083:80
    volumes:
      # - ./docker/default.conf:/etc/nginx/conf.d/default.conf
      - ./dist:/usr/share/nginx/html
